// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/task.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 任务状态
type TaskStatus int32

const (
	TaskStatus_task_status_not_executing TaskStatus = 0
	TaskStatus_task_status_executing     TaskStatus = 1
	TaskStatus_task_status_executed      TaskStatus = 2
	TaskStatus_task_status_cancel        TaskStatus = 3
	TaskStatus_task_status_fail          TaskStatus = 4
)

var TaskStatus_name = map[int32]string{
	0: "task_status_not_executing",
	1: "task_status_executing",
	2: "task_status_executed",
	3: "task_status_cancel",
	4: "task_status_fail",
}
var TaskStatus_value = map[string]int32{
	"task_status_not_executing": 0,
	"task_status_executing":     1,
	"task_status_executed":      2,
	"task_status_cancel":        3,
	"task_status_fail":          4,
}

func (x TaskStatus) String() string {
	return proto.EnumName(TaskStatus_name, int32(x))
}
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_task_934f59546a9e0b01, []int{0}
}

// http请求的类型
type TaskExecuteMethod int32

const (
	TaskExecuteMethod_grpc   TaskExecuteMethod = 0
	TaskExecuteMethod_get    TaskExecuteMethod = 1
	TaskExecuteMethod_post   TaskExecuteMethod = 2
	TaskExecuteMethod_put    TaskExecuteMethod = 3
	TaskExecuteMethod_delete TaskExecuteMethod = 4
)

var TaskExecuteMethod_name = map[int32]string{
	0: "grpc",
	1: "get",
	2: "post",
	3: "put",
	4: "delete",
}
var TaskExecuteMethod_value = map[string]int32{
	"grpc":   0,
	"get":    1,
	"post":   2,
	"put":    3,
	"delete": 4,
}

func (x TaskExecuteMethod) String() string {
	return proto.EnumName(TaskExecuteMethod_name, int32(x))
}
func (TaskExecuteMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_task_934f59546a9e0b01, []int{1}
}

type Task struct {
	Id                   uint64               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,2,opt,name=createTime,proto3" json:"createTime,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	NextTime             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=nextTime,proto3" json:"nextTime,omitempty"`
	Status               TaskStatus           `protobuf:"varint,5,opt,name=status,proto3,enum=proto.TaskStatus" json:"status,omitempty"`
	Method               TaskExecuteMethod    `protobuf:"varint,6,opt,name=method,proto3,enum=proto.TaskExecuteMethod" json:"method,omitempty"`
	Url                  string               `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_task_934f59546a9e0b01, []int{0}
}
func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (dst *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(dst, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Task) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Task) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *Task) GetNextTime() *timestamp.Timestamp {
	if m != nil {
		return m.NextTime
	}
	return nil
}

func (m *Task) GetStatus() TaskStatus {
	if m != nil {
		return m.Status
	}
	return TaskStatus_task_status_not_executing
}

func (m *Task) GetMethod() TaskExecuteMethod {
	if m != nil {
		return m.Method
	}
	return TaskExecuteMethod_grpc
}

func (m *Task) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type CreateRequest struct {
	Duration             int64             `protobuf:"varint,1,opt,name=duration,proto3" json:"duration,omitempty"`
	Url                  string            `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Status               TaskExecuteMethod `protobuf:"varint,3,opt,name=status,proto3,enum=proto.TaskExecuteMethod" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_task_934f59546a9e0b01, []int{1}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(dst, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *CreateRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CreateRequest) GetStatus() TaskExecuteMethod {
	if m != nil {
		return m.Status
	}
	return TaskExecuteMethod_grpc
}

type CreateResponse struct {
	Task                 *Task    `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_task_934f59546a9e0b01, []int{2}
}
func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (dst *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(dst, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func init() {
	proto.RegisterType((*Task)(nil), "proto.Task")
	proto.RegisterType((*CreateRequest)(nil), "proto.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "proto.CreateResponse")
	proto.RegisterEnum("proto.TaskStatus", TaskStatus_name, TaskStatus_value)
	proto.RegisterEnum("proto.TaskExecuteMethod", TaskExecuteMethod_name, TaskExecuteMethod_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TaskServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type taskServiceClient struct {
	cc *grpc.ClientConn
}

func NewTaskServiceClient(cc *grpc.ClientConn) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/proto.TaskService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
type TaskServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
}

func RegisterTaskServiceServer(s *grpc.Server, srv TaskServiceServer) {
	s.RegisterService(&_TaskService_serviceDesc, srv)
}

func _TaskService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TaskService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TaskService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TaskService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/task.proto",
}

func init() { proto.RegisterFile("proto/task.proto", fileDescriptor_task_934f59546a9e0b01) }

var fileDescriptor_task_934f59546a9e0b01 = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0x7f, 0xea, 0x86, 0x89, 0x88, 0xb6, 0xa3, 0x14, 0xb9, 0x91, 0x50, 0xa3, 0x9c, 0x42,
	0x0f, 0x0e, 0x04, 0x09, 0x24, 0xae, 0xa8, 0xdc, 0xb8, 0x98, 0xdc, 0x23, 0xd7, 0x9e, 0x1a, 0xab,
	0x8e, 0xd7, 0x78, 0x67, 0x51, 0x9f, 0x82, 0xb7, 0xe1, 0xfd, 0xd0, 0xae, 0xed, 0xc4, 0x34, 0x87,
	0x9c, 0x76, 0xf7, 0xfb, 0x99, 0x99, 0x6f, 0x16, 0x44, 0xdd, 0x48, 0x96, 0x6b, 0x4e, 0xd4, 0x53,
	0x64, 0xaf, 0x78, 0x61, 0x8f, 0xf9, 0x6d, 0x2e, 0x65, 0x5e, 0xd2, 0xda, 0xbe, 0x1e, 0xf4, 0xe3,
	0x9a, 0x8b, 0x3d, 0x29, 0x4e, 0xf6, 0x75, 0xab, 0x5b, 0xfe, 0x75, 0xc1, 0xdf, 0x26, 0xea, 0x09,
	0xa7, 0xe0, 0x16, 0x59, 0xe8, 0x2c, 0x9c, 0x95, 0x1f, 0xbb, 0x45, 0x86, 0x5f, 0x00, 0xd2, 0x86,
	0x12, 0xa6, 0x6d, 0xb1, 0xa7, 0xd0, 0x5d, 0x38, 0xab, 0xc9, 0x66, 0x1e, 0xb5, 0xe5, 0xa2, 0xbe,
	0x5c, 0xb4, 0xed, 0xcb, 0xc5, 0x03, 0xb5, 0xf1, 0xea, 0x3a, 0xeb, 0xbd, 0xde, 0x79, 0xef, 0x51,
	0x8d, 0x9f, 0x60, 0x5c, 0xd1, 0x33, 0x5b, 0xa7, 0x7f, 0xd6, 0x79, 0xd0, 0xe2, 0x3b, 0x08, 0x14,
	0x27, 0xac, 0x55, 0x78, 0xb1, 0x70, 0x56, 0xd3, 0xcd, 0x55, 0x2b, 0x8f, 0x4c, 0xb8, 0x1f, 0x96,
	0x88, 0x3b, 0x01, 0xbe, 0x87, 0x60, 0x4f, 0xfc, 0x53, 0x66, 0x61, 0x60, 0xa5, 0xe1, 0x40, 0x7a,
	0xff, 0x4c, 0xa9, 0x66, 0xfa, 0x6e, 0xf9, 0xb8, 0xd3, 0xa1, 0x00, 0x4f, 0x37, 0x65, 0x78, 0xb9,
	0x70, 0x56, 0xaf, 0x62, 0x73, 0x5d, 0x4a, 0x78, 0xfd, 0xd5, 0x06, 0x8e, 0xe9, 0x97, 0x26, 0xc5,
	0x38, 0x87, 0x71, 0xa6, 0x9b, 0x84, 0x0b, 0x59, 0xd9, 0x2d, 0x7a, 0xf1, 0xe1, 0xdd, 0xdb, 0xdd,
	0x83, 0xdd, 0x8c, 0xd0, 0x4d, 0xeb, 0x9d, 0x1b, 0xa1, 0xd5, 0x2d, 0x3f, 0xc0, 0xb4, 0x6f, 0xa8,
	0x6a, 0x59, 0x29, 0xc2, 0x5b, 0xf0, 0xcd, 0x87, 0xdb, 0x6e, 0x93, 0xcd, 0x64, 0x50, 0x21, 0xb6,
	0xc4, 0xdd, 0x1f, 0x07, 0xe0, 0x18, 0x1f, 0xdf, 0xc2, 0x8d, 0x81, 0x77, 0x6d, 0xc1, 0x5d, 0x25,
	0x79, 0x47, 0xb6, 0x55, 0x51, 0xe5, 0x62, 0x84, 0x37, 0x70, 0x3d, 0xa4, 0x8f, 0x94, 0x83, 0x21,
	0xcc, 0x4e, 0x29, 0xca, 0x84, 0x8b, 0x6f, 0x00, 0x87, 0x4c, 0x9a, 0x54, 0x29, 0x95, 0xc2, 0xc3,
	0x19, 0x88, 0x21, 0xfe, 0x98, 0x14, 0xa5, 0xf0, 0xef, 0xee, 0xe1, 0xea, 0x24, 0x20, 0x8e, 0xc1,
	0xcf, 0x9b, 0x3a, 0x15, 0x23, 0xbc, 0x04, 0x2f, 0x27, 0x16, 0x8e, 0x81, 0x6a, 0xa9, 0x58, 0xb8,
	0x06, 0xaa, 0x35, 0x0b, 0x0f, 0x01, 0x82, 0x8c, 0x4a, 0x62, 0x12, 0xfe, 0xe6, 0x1b, 0x4c, 0x6c,
	0x2c, 0x6a, 0x7e, 0x17, 0x29, 0xe1, 0x67, 0x08, 0xda, 0xcd, 0xe0, 0xac, 0xdb, 0xc1, 0x7f, 0x3f,
	0x33, 0xbf, 0x7e, 0x81, 0xb6, 0xeb, 0x5b, 0x8e, 0x1e, 0x02, 0x8b, 0x7f, 0xfc, 0x17, 0x00, 0x00,
	0xff, 0xff, 0x92, 0xdc, 0xdd, 0x2a, 0x3e, 0x03, 0x00, 0x00,
}
